version: '3'

services:
  nginx-container:
    image: nginx:latest
    container_name: "${NAME}"
    ports:
      - "${PORT:-83}:80"
    labels:
      - branch="${BRANCH:-develop}"
      - version=5
    environment:
      - LABEL=abcdddd      
