version: '3'
services:
 large-app:
  image: 6261998/alpine:latest
  volumes:
      - ./html:/home/html
  tty: true
  stdin_open: true
  environment:
   - ${ENV:-default}=novigrad
   - ${ENV2:-default2}=raphael
   - ${ENV3:-default3}=esm
   - ${ENV4}=${ENV4}
